# Generated by Django 4.0.5 on 2022-07-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_comentariocontacto_alter_alumnos_options_and_more'),
        ('registros', '0004_comentariocontacto_alter_comentario_coment'),
    ]

    operations = [
    ]
