# Generated by Django 4.0.5 on 2022-07-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_merge_20220713_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='comentariocontacto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='comentariocontacto',
            name='usuario',
            field=models.TextField(verbose_name='Usuario'),
        ),
    ]
