# Generated by Django 4.0.5 on 2022-08-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_alumnos_imagen_and_more'),
        ('registros', '0009_archivos_alter_alumnos_id'),
    ]

    operations = [
    ]
